Response style changed
Anna-Assistant/Anna pull request #55
Opened 2017-12-12 12:47 UTC by gautamramuvel

2017-12-12 13:20 UTC, gauthamzz commented
files are again changed in so many unwanted places. This issue requires changing of one or two lines at max :smile:

2017-12-12 13:22 UTC, gauthamzz requested changes

2017-12-12 13:22 UTC, gauthamzz commented on background.js
> +        alert(txt);
why are you alrerting ?

2017-12-12 13:22 UTC, gauthamzz commented on background.js
> +    function tasks() {
why is this even changed :small_airplane:

2017-12-12 14:21 UTC, gautamramuvel commented
It's the same code

2017-12-14 13:14 UTC, gauthamzz commented
Are you working on this ?

2017-12-15 10:08 UTC, gautamramuvel commented
It's done..

On 14-Dec-2017 6:44 PM, "Gautham Santhosh" <notifications@github.com> wrote:

> Are you working on this ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Anna-Assistant/Anna/pull/55#issuecomment-351707494>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQEzFUBI2Lq-lrRtUcH2aWHtMCbY2-Hnks5tAR9MgaJpZM4Q-6j5>
> .
>

2017-12-15 10:08 UTC, gautamramuvel commented
I'm yet to push

On 15-Dec-2017 3:38 PM, "Gautam Ramuvel" <gautam.ramuvel15@gmail.com> wrote:

> It's done..
>
> On 14-Dec-2017 6:44 PM, "Gautham Santhosh" <notifications@github.com>
> wrote:
>
>> Are you working on this ?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Anna-Assistant/Anna/pull/55#issuecomment-351707494>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AQEzFUBI2Lq-lrRtUcH2aWHtMCbY2-Hnks5tAR9MgaJpZM4Q-6j5>
>> .
>>
>

2017-12-17 03:56 UTC, closed without merging